platform :ios, '10.0'
inhibit_all_warnings!


target 'StickerKeyboard' do
  use_frameworks!
  all_binary!
  enable_bitcode_for_prebuilt_frameworks!

 
    pod 'Kingfisher'                            , '~>5.12.0'
                  
  
end
